### ISSUE TITLE
How do I introduce this library?

### ISSUE THREAD

**Issue by AnglerDW** [marijnvdwerf/material-palette#2]
i installed material-palette from npm,  but I find it's different from the github version

**Comment by evelynhathaway** [comment]
[`material-palette`](https://www.npmjs.com/package/material-palette) on npm is a [different library](https://github.com/leodido/material-palette).

If you're wanting to use this library instead tell npm to install it via git as there's currently no npm releases for it.
```bash
npm install --save github:marijnvdwerf/material-palette#ec1bfed
```
Replace `ec1bfed` with the commit or branch you'd like to install to protect yourself from breaking changes.

**Comment by marijnvdwerf** [comment]
Thanks for the explanation @evelynhathaway.

General disclaimer: I made this a *long* time ago, and only really for a single local-running prototype. So don't expect too much of it performance-wise.

**Comment by AnglerDW** [comment]
@evelynhathaway  Thank you for your explanation, It helps me a lot.
